apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Используем Let's Encrypt для выдачи сертификатов
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sajpidinovaajperi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx